const DATA = [
  {
    "id": "rec0CSulsUDdH2z5E",
    "nome": "Bistrot Al Campanile",
    "segmento": "Bistrot",
    "dataSignup": "2025-12-19",
    "healthScore": 30,
    "healthZone": "red",
    "loginGG": 2,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 34,
    "pagamenti": "overdue",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 2,
    "ticketCS": 3,
    "prioritaCS": true,
    "scansioni": 1,
    "interazioni": 1,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "NPS basso: difficolta con la sezione foto",
    "sintesiInterazione": "Cliente chiede il prezzo del menu fisso serale",
    "modificheRichieste": 2,
    "modificheRisolte": 1,
    "interazioneRisolta": false,
    "mediaCoperti": 69
  },
  {
    "id": "rec21cwCRxYJuV3AW",
    "nome": "Resort Bella Napoli",
    "segmento": "Agriturismo",
    "dataSignup": "2025-09-16",
    "healthScore": 74,
    "healthZone": "green",
    "loginGG": 30,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 90,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "obtained",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 586,
    "interazioni": 442,
    "postVisti": 4,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "Domanda su esportazione PDF del menu",
    "sintesiInterazione": "Ordine room service tramite menu digitale camera 14",
    "modificheRichieste": 4,
    "modificheRisolte": 4,
    "interazioneRisolta": true,
    "mediaCoperti": 150
  },
  {
    "id": "rec2BpOnsKYmEGrbs",
    "nome": "Locanda Nuovo Aperto",
    "segmento": "Resort",
    "dataSignup": "2025-11-03",
    "healthScore": 53,
    "healthZone": "yellow",
    "loginGG": 8,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 57,
    "pagamenti": "overdue",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 7,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 97,
    "interazioni": 78,
    "postVisti": 1,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Domanda su integrazione con sistema cassa",
    "sintesiInterazione": "Info vini in abbinamento al menu degustazione",
    "modificheRichieste": 7,
    "modificheRisolte": 6,
    "interazioneRisolta": false,
    "mediaCoperti": 53
  },
  {
    "id": "rec2RGVQOd5ypkjlw",
    "nome": "Locanda Da Antonio",
    "segmento": "Bar Ristorante",
    "dataSignup": "2025-09-24",
    "healthScore": 87,
    "healthZone": "green",
    "loginGG": 22,
    "moduliAttivati": 4,
    "moduliTotali": 5,
    "completezza": 94,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "obtained",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 689,
    "interazioni": 540,
    "postVisti": 5,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "Configurazione menu per evento privato",
    "sintesiInterazione": "Preordine tavolo 6 — antipasto e primo per 4 persone",
    "modificheRichieste": 11,
    "modificheRisolte": 11,
    "interazioneRisolta": true,
    "mediaCoperti": 161
  },
  {
    "id": "rec2WGkjfMG26dUAq",
    "nome": "Braceria Veneto",
    "segmento": "Pub",
    "dataSignup": "2026-01-18",
    "healthScore": 89,
    "healthZone": "green",
    "loginGG": 17,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 98,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "obtained",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 9,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 598,
    "interazioni": 412,
    "postVisti": 11,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Configurazione orari di apertura",
    "sintesiInterazione": "Cliente chiede versione light del menu degustazione",
    "modificheRichieste": 10,
    "modificheRisolte": 10,
    "interazioneRisolta": true,
    "mediaCoperti": 96
  },
  {
    "id": "rec2kYJpYYSm1U7U6",
    "nome": "Braceria La Terrazza",
    "segmento": "Trattoria",
    "dataSignup": "2026-01-28",
    "healthScore": 44,
    "healthZone": "yellow",
    "loginGG": 9,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 54,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "shown",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 25,
    "interazioni": 19,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Domanda su esportazione PDF del menu",
    "sintesiInterazione": "Cliente chiede il prezzo del menu fisso serale",
    "modificheRichieste": 7,
    "modificheRisolte": 5,
    "interazioneRisolta": true,
    "mediaCoperti": 54
  },
  {
    "id": "rec3T3mCTeJDJfjwV",
    "nome": "Osteria La Fontana",
    "segmento": "Bistrot",
    "dataSignup": "2026-02-28",
    "healthScore": 11,
    "healthZone": "red",
    "loginGG": 3,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 22,
    "pagamenti": "failed",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 5,
    "prioritaCS": true,
    "scansioni": 14,
    "interazioni": 14,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Problema upload foto secondi piatti",
    "sintesiInterazione": "Info vini in abbinamento al menu degustazione",
    "modificheRichieste": 2,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 36
  },
  {
    "id": "rec43DZy3JF937Q7j",
    "nome": "Locanda Alla Vecchia Maniera",
    "segmento": "Braceria",
    "dataSignup": "2026-03-17",
    "healthScore": 0,
    "healthZone": "unknown",
    "loginGG": 3,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 25,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 0,
    "interazioni": 0,
    "postVisti": 0,
    "tipoUltimaInterazione": "",
    "sintesiChat": "Non riesce a pubblicare il menu — bloccato in bozza",
    "sintesiInterazione": "Nessuna interazione registrata",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 23
  },
  {
    "id": "rec4EPTrB4zzrz11B",
    "nome": "Enoteca Sakura",
    "segmento": "Trattoria",
    "dataSignup": "2025-09-09",
    "healthScore": 82,
    "healthZone": "green",
    "loginGG": 27,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 86,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 9,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 410,
    "interazioni": 305,
    "postVisti": 11,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Non riesce a pubblicare il menu — bloccato in bozza",
    "sintesiInterazione": "Cliente chiede versione light del menu degustazione",
    "modificheRichieste": 18,
    "modificheRisolte": 18,
    "interazioneRisolta": true,
    "mediaCoperti": 194
  },
  {
    "id": "rec4RkDgvyBNZzeyX",
    "nome": "Taverna Al Campanile",
    "segmento": "Ristorante",
    "dataSignup": "2026-01-22",
    "healthScore": 75,
    "healthZone": "green",
    "loginGG": 24,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 87,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 9,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 299,
    "interazioni": 238,
    "postVisti": 11,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "Non riesce a pubblicare il menu — bloccato in bozza",
    "sintesiInterazione": "Ordine room service tramite menu digitale camera 14",
    "modificheRichieste": 4,
    "modificheRisolte": 4,
    "interazioneRisolta": true,
    "mediaCoperti": 164
  },
  {
    "id": "rec4z8c2vjFtXsFl5",
    "nome": "Pub & Cucina Del Corso",
    "segmento": "Bistrot",
    "dataSignup": "2025-11-13",
    "healthScore": 82,
    "healthZone": "green",
    "loginGG": 21,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 79,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 512,
    "interazioni": 388,
    "postVisti": 5,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Problema con pagamento abbonamento",
    "sintesiInterazione": "Cliente chiede dettagli su piatto del giorno",
    "modificheRichieste": 12,
    "modificheRisolte": 12,
    "interazioneRisolta": true,
    "mediaCoperti": 197
  },
  {
    "id": "rec67MhrysQmuntJb",
    "nome": "Taverna Il Mulino",
    "segmento": "Osteria",
    "dataSignup": "2025-12-22",
    "healthScore": 98,
    "healthZone": "green",
    "loginGG": 25,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 80,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "applied",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 9,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 348,
    "interazioni": 243,
    "postVisti": 6,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Domanda su integrazione con sistema cassa",
    "sintesiInterazione": "Domanda se il locale e adatto a celiaci",
    "modificheRichieste": 4,
    "modificheRisolte": 4,
    "interazioneRisolta": true,
    "mediaCoperti": 108
  },
  {
    "id": "rec6OofHU1yyGfI2p",
    "nome": "Osteria Lombarda",
    "segmento": "Bar Ristorante",
    "dataSignup": "2026-03-06",
    "healthScore": 0,
    "healthZone": "unknown",
    "loginGG": 4,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 15,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 0,
    "interazioni": 0,
    "postVisti": 0,
    "tipoUltimaInterazione": "",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Nessuna interazione registrata",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 50
  },
  {
    "id": "rec6jRx0jL2LMzb7m",
    "nome": "Agriturismo Alla Vecchia Maniera",
    "segmento": "Osteria",
    "dataSignup": "2025-12-26",
    "healthScore": 84,
    "healthZone": "green",
    "loginGG": 29,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 84,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 277,
    "interazioni": 217,
    "postVisti": 7,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Nessuna interazione recente",
    "sintesiInterazione": "Richiesta porzione ridotta per menu bambini",
    "modificheRichieste": 20,
    "modificheRisolte": 20,
    "interazioneRisolta": true,
    "mediaCoperti": 66
  },
  {
    "id": "rec7RiBwhlWMdK9CJ",
    "nome": "Locanda Recente",
    "segmento": "Bar Ristorante",
    "dataSignup": "2026-01-06",
    "healthScore": 62,
    "healthZone": "yellow",
    "loginGG": 4,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 51,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "shown",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": false,
    "nps": 8,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 72,
    "interazioni": 59,
    "postVisti": 2,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Domanda su presenza crostacei nel ramen di miso",
    "modificheRichieste": 1,
    "modificheRisolte": 0,
    "interazioneRisolta": true,
    "mediaCoperti": 43
  },
  {
    "id": "rec88VQnBtfsHU6KR",
    "nome": "Resort Da Luigi",
    "segmento": "Resort",
    "dataSignup": "2025-12-30",
    "healthScore": 1,
    "healthZone": "red",
    "loginGG": 0,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 26,
    "pagamenti": "overdue",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 1,
    "ticketCS": 4,
    "prioritaCS": true,
    "scansioni": 1,
    "interazioni": 1,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Problema upload foto secondi piatti",
    "sintesiInterazione": "Domanda su certificazione biologica delle verdure",
    "modificheRichieste": 4,
    "modificheRisolte": 1,
    "interazioneRisolta": false,
    "mediaCoperti": 42
  },
  {
    "id": "rec8VvwFShUeZ3BDC",
    "nome": "Locanda Al Campanile",
    "segmento": "Braceria",
    "dataSignup": "2026-02-18",
    "healthScore": 48,
    "healthZone": "yellow",
    "loginGG": 4,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 63,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 7,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 48,
    "interazioni": 39,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "NPS basso: difficolta con la sezione foto",
    "sintesiInterazione": "Aggiornamento descrizione secondo piatto — nuova ricetta",
    "modificheRichieste": 6,
    "modificheRisolte": 4,
    "interazioneRisolta": false,
    "mediaCoperti": 68
  },
  {
    "id": "rec8ffYvdOAVESFGF",
    "nome": "Bar Ristorante Il Castello",
    "segmento": "Bistrot",
    "dataSignup": "2025-12-16",
    "healthScore": 79,
    "healthZone": "green",
    "loginGG": 19,
    "moduliAttivati": 4,
    "moduliTotali": 5,
    "completezza": 80,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "shown",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 534,
    "interazioni": 379,
    "postVisti": 3,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Segnalazione QR code non leggibile su alcuni tavoli",
    "sintesiInterazione": "Richiesta porzione ridotta per menu bambini",
    "modificheRichieste": 18,
    "modificheRisolte": 18,
    "interazioneRisolta": true,
    "mediaCoperti": 181
  },
  {
    "id": "rec8h4m9MsZ1yrB12",
    "nome": "Hotel Bianco",
    "segmento": "Trattoria",
    "dataSignup": "2026-01-15",
    "healthScore": 35,
    "healthZone": "red",
    "loginGG": 2,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 16,
    "pagamenti": "overdue",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 3,
    "ticketCS": 3,
    "prioritaCS": true,
    "scansioni": 1,
    "interazioni": 1,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Segnalazione QR code non leggibile su alcuni tavoli",
    "sintesiInterazione": "Cliente chiede ingredienti della zuppa di pesce",
    "modificheRichieste": 3,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 22
  },
  {
    "id": "rec915BkBz5XbF41W",
    "nome": "Sushi Bar Nuovo Aperto",
    "segmento": "Bar Ristorante",
    "dataSignup": "2026-01-22",
    "healthScore": 81,
    "healthZone": "green",
    "loginGG": 29,
    "moduliAttivati": 4,
    "moduliTotali": 5,
    "completezza": 96,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 8,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 778,
    "interazioni": 523,
    "postVisti": 10,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "Non riesce a pubblicare il menu — bloccato in bozza",
    "sintesiInterazione": "Preordine tavolo 6 — antipasto e primo per 4 persone",
    "modificheRichieste": 17,
    "modificheRisolte": 17,
    "interazioneRisolta": true,
    "mediaCoperti": 67
  },
  {
    "id": "recAAxxMBIjo6VH9l",
    "nome": "Bar Ristorante Ai Portici",
    "segmento": "Bistrot",
    "dataSignup": "2026-02-14",
    "healthScore": 51,
    "healthZone": "yellow",
    "loginGG": 4,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 69,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 7,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 110,
    "interazioni": 80,
    "postVisti": 3,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Richiesta attivazione modulo prenotazioni",
    "sintesiInterazione": "Aggiornamento descrizione secondo piatto — nuova ricetta",
    "modificheRichieste": 1,
    "modificheRisolte": 0,
    "interazioneRisolta": true,
    "mediaCoperti": 54
  },
  {
    "id": "recBopNaPeO2iRdAO",
    "nome": "Resort La Fontana",
    "segmento": "Sushi Bar",
    "dataSignup": "2026-01-25",
    "healthScore": 28,
    "healthZone": "red",
    "loginGG": 1,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 13,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 3,
    "ticketCS": 2,
    "prioritaCS": true,
    "scansioni": 9,
    "interazioni": 7,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Problema con pagamento abbonamento",
    "sintesiInterazione": "Info vini in abbinamento al menu degustazione",
    "modificheRichieste": 2,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 46
  },
  {
    "id": "recCCYD79ywW4cAgv",
    "nome": "Bistrot Napoli Vera",
    "segmento": "Bar Ristorante",
    "dataSignup": "2025-10-26",
    "healthScore": 88,
    "healthZone": "green",
    "loginGG": 30,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 75,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "obtained",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 8,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 454,
    "interazioni": 346,
    "postVisti": 5,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Richiesta supporto per traduzione menu in inglese",
    "sintesiInterazione": "Cliente chiede il prezzo del menu fisso serale",
    "modificheRichieste": 13,
    "modificheRisolte": 13,
    "interazioneRisolta": true,
    "mediaCoperti": 52
  },
  {
    "id": "recCZRURzxEhVTZTi",
    "nome": "Bar Ristorante La Pergola",
    "segmento": "Ristorante",
    "dataSignup": "2025-11-13",
    "healthScore": 98,
    "healthZone": "green",
    "loginGG": 29,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 79,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "obtained",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 666,
    "interazioni": 504,
    "postVisti": 6,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Richiesta supporto per traduzione menu in inglese",
    "sintesiInterazione": "Cliente chiede versione light del menu degustazione",
    "modificheRichieste": 16,
    "modificheRisolte": 16,
    "interazioneRisolta": true,
    "mediaCoperti": 56
  },
  {
    "id": "recEbfonSCLbyGfUa",
    "nome": "Agriturismo Il Faro",
    "segmento": "Bar Ristorante",
    "dataSignup": "2025-09-26",
    "healthScore": 84,
    "healthZone": "green",
    "loginGG": 15,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 82,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 106,
    "interazioni": 87,
    "postVisti": 12,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Nessuna interazione recente",
    "sintesiInterazione": "Richiesta piatto senza lattosio — pizza con mozzarella vegana",
    "modificheRichieste": 10,
    "modificheRisolte": 10,
    "interazioneRisolta": true,
    "mediaCoperti": 96
  },
  {
    "id": "recEe7yjtfCTBP2Ea",
    "nome": "Trattoria Siciliana",
    "segmento": "Agriturismo",
    "dataSignup": "2025-11-23",
    "healthScore": 42,
    "healthZone": "yellow",
    "loginGG": 8,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 73,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 5,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 82,
    "interazioni": 59,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Problema upload foto secondi piatti",
    "sintesiInterazione": "Cliente vuole sostituire la carne con alternativa vegetariana",
    "modificheRichieste": 1,
    "modificheRisolte": 0,
    "interazioneRisolta": true,
    "mediaCoperti": 65
  },
  {
    "id": "recFuxkcLqOKaBLfo",
    "nome": "Locanda Tokyo Garden",
    "segmento": "Ristorante",
    "dataSignup": "2025-12-04",
    "healthScore": 1,
    "healthZone": "red",
    "loginGG": 3,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 40,
    "pagamenti": "overdue",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 6,
    "ticketCS": 2,
    "prioritaCS": true,
    "scansioni": 1,
    "interazioni": 1,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Non riesce a pubblicare il menu — bloccato in bozza",
    "sintesiInterazione": "Cliente chiede ingredienti della zuppa di pesce",
    "modificheRichieste": 4,
    "modificheRisolte": 1,
    "interazioneRisolta": false,
    "mediaCoperti": 34
  },
  {
    "id": "recG3c0jJyAjSRpn5",
    "nome": "Ristorante Da Nonna Rosa",
    "segmento": "Braceria",
    "dataSignup": "2025-09-11",
    "healthScore": 100,
    "healthZone": "green",
    "loginGG": 14,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 98,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 318,
    "interazioni": 249,
    "postVisti": 5,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Nessuna interazione recente",
    "sintesiInterazione": "Modifica prezzi sezione antipasti — aumento stagionale",
    "modificheRichieste": 16,
    "modificheRisolte": 16,
    "interazioneRisolta": false,
    "mediaCoperti": 161
  },
  {
    "id": "recGIotvl6YezOf35",
    "nome": "Pub & Cucina Fuji",
    "segmento": "Bistrot",
    "dataSignup": "2026-03-15",
    "healthScore": 0,
    "healthZone": "unknown",
    "loginGG": 1,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 22,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 0,
    "interazioni": 0,
    "postVisti": 0,
    "tipoUltimaInterazione": "",
    "sintesiChat": "Problema con pagamento abbonamento",
    "sintesiInterazione": "Nessuna interazione registrata",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 79
  },
  {
    "id": "recGqx5I2UCr65xc4",
    "nome": "Bar Ristorante Fuji",
    "segmento": "Pizzeria",
    "dataSignup": "2025-10-31",
    "healthScore": 75,
    "healthZone": "green",
    "loginGG": 15,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 84,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 9,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 346,
    "interazioni": 283,
    "postVisti": 9,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Domanda su esportazione PDF del menu",
    "sintesiInterazione": "Aggiunta nota allergeni alla zuppa di pesce",
    "modificheRichieste": 10,
    "modificheRisolte": 10,
    "interazioneRisolta": true,
    "mediaCoperti": 141
  },
  {
    "id": "recIxSmNSdVfdVJ0a",
    "nome": "Braceria Nuovo Aperto",
    "segmento": "Sushi Bar",
    "dataSignup": "2025-11-16",
    "healthScore": 83,
    "healthZone": "green",
    "loginGG": 28,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 87,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 367,
    "interazioni": 281,
    "postVisti": 9,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Ordine room service tramite menu digitale camera 14",
    "modificheRichieste": 13,
    "modificheRisolte": 13,
    "interazioneRisolta": true,
    "mediaCoperti": 40
  },
  {
    "id": "recJjnKHVmRlUCtwh",
    "nome": "Pub & Cucina Ichiban",
    "segmento": "Pizzeria",
    "dataSignup": "2025-11-16",
    "healthScore": 77,
    "healthZone": "green",
    "loginGG": 20,
    "moduliAttivati": 4,
    "moduliTotali": 5,
    "completezza": 79,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "applied",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 9,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 761,
    "interazioni": 549,
    "postVisti": 4,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Configurazione menu per evento privato",
    "sintesiInterazione": "Sostituzione guarnizione sul filetto — preferenza cliente",
    "modificheRichieste": 6,
    "modificheRisolte": 6,
    "interazioneRisolta": true,
    "mediaCoperti": 42
  },
  {
    "id": "recJz0buawVQ4uV8h",
    "nome": "Ristorante Alla Vecchia Maniera",
    "segmento": "Sushi Bar",
    "dataSignup": "2026-01-02",
    "healthScore": 51,
    "healthZone": "yellow",
    "loginGG": 9,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 55,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 32,
    "interazioni": 28,
    "postVisti": 1,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Problema upload foto secondi piatti",
    "sintesiInterazione": "Aggiornamento descrizione secondo piatto — nuova ricetta",
    "modificheRichieste": 8,
    "modificheRisolte": 7,
    "interazioneRisolta": false,
    "mediaCoperti": 56
  },
  {
    "id": "recKBqXaJkrpmrXbR",
    "nome": "Braceria Fresh",
    "segmento": "Agriturismo",
    "dataSignup": "2025-11-29",
    "healthScore": 69,
    "healthZone": "yellow",
    "loginGG": 5,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 45,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 7,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 23,
    "interazioni": 20,
    "postVisti": 1,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Cliente chiede versione light del menu degustazione",
    "modificheRichieste": 6,
    "modificheRisolte": 6,
    "interazioneRisolta": false,
    "mediaCoperti": 63
  },
  {
    "id": "recKOHHhlOLqWOZuY",
    "nome": "Taverna Il Rifugio",
    "segmento": "Resort",
    "dataSignup": "2026-02-21",
    "healthScore": 1,
    "healthZone": "red",
    "loginGG": 0,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 40,
    "pagamenti": "overdue",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 4,
    "ticketCS": 1,
    "prioritaCS": true,
    "scansioni": 15,
    "interazioni": 13,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Domanda su certificazione biologica delle verdure",
    "modificheRichieste": 3,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 33
  },
  {
    "id": "recKnPWZiynN2YOP2",
    "nome": "Resort Napoli Vera",
    "segmento": "Braceria",
    "dataSignup": "2026-01-14",
    "healthScore": 35,
    "healthZone": "red",
    "loginGG": 2,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 35,
    "pagamenti": "failed",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 1,
    "ticketCS": 4,
    "prioritaCS": true,
    "scansioni": 2,
    "interazioni": 2,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Richiesta attivazione modulo prenotazioni",
    "sintesiInterazione": "Cliente chiede dettagli su piatto del giorno",
    "modificheRichieste": 4,
    "modificheRisolte": 2,
    "interazioneRisolta": false,
    "mediaCoperti": 25
  },
  {
    "id": "recLG9Kcbz1BZk5MG",
    "nome": "Resort Veneto",
    "segmento": "Bistrot",
    "dataSignup": "2025-12-13",
    "healthScore": 86,
    "healthZone": "green",
    "loginGG": 27,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 80,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "applied",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 252,
    "interazioni": 175,
    "postVisti": 12,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Non riesce a pubblicare il menu — bloccato in bozza",
    "sintesiInterazione": "Richiesta aggiunta opzione vegana alla pasta al pesto",
    "modificheRichieste": 12,
    "modificheRisolte": 12,
    "interazioneRisolta": true,
    "mediaCoperti": 125
  },
  {
    "id": "recMgH4uBkH9I158w",
    "nome": "Pizzeria Il Faro",
    "segmento": "Braceria",
    "dataSignup": "2025-10-20",
    "healthScore": 51,
    "healthZone": "yellow",
    "loginGG": 7,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 67,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 48,
    "interazioni": 40,
    "postVisti": 3,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Domanda su esportazione PDF del menu",
    "sintesiInterazione": "Cliente chiede il prezzo del menu fisso serale",
    "modificheRichieste": 5,
    "modificheRisolte": 3,
    "interazioneRisolta": true,
    "mediaCoperti": 31
  },
  {
    "id": "recNm8XAL3mvzpOhI",
    "nome": "Bar Ristorante La Cantina",
    "segmento": "Agriturismo",
    "dataSignup": "2025-11-24",
    "healthScore": 87,
    "healthZone": "green",
    "loginGG": 12,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 81,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "obtained",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 9,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 776,
    "interazioni": 582,
    "postVisti": 6,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Problema con pagamento abbonamento",
    "sintesiInterazione": "Modifica prezzi sezione antipasti — aumento stagionale",
    "modificheRichieste": 12,
    "modificheRisolte": 12,
    "interazioneRisolta": true,
    "mediaCoperti": 161
  },
  {
    "id": "recOfbd3LwygmIrwn",
    "nome": "Osteria Ai Tre Archi",
    "segmento": "Pizzeria",
    "dataSignup": "2025-11-26",
    "healthScore": 55,
    "healthZone": "yellow",
    "loginGG": 6,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 62,
    "pagamenti": "overdue",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": false,
    "nps": 5,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 48,
    "interazioni": 44,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Problema upload foto secondi piatti",
    "sintesiInterazione": "Cliente chiede ingredienti della zuppa di pesce",
    "modificheRichieste": 5,
    "modificheRisolte": 4,
    "interazioneRisolta": true,
    "mediaCoperti": 63
  },
  {
    "id": "recOxDiIvO24eCYbs",
    "nome": "Pizzeria Del Porto",
    "segmento": "Osteria",
    "dataSignup": "2026-02-14",
    "healthScore": 41,
    "healthZone": "yellow",
    "loginGG": 7,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 47,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "shown",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 6,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 39,
    "interazioni": 29,
    "postVisti": 3,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Problema con pagamento abbonamento",
    "sintesiInterazione": "Domanda su certificazione biologica delle verdure",
    "modificheRichieste": 8,
    "modificheRisolte": 6,
    "interazioneRisolta": false,
    "mediaCoperti": 62
  },
  {
    "id": "recP6neSjHselBfxl",
    "nome": "Resort Le Colline",
    "segmento": "Agriturismo",
    "dataSignup": "2025-12-05",
    "healthScore": 3,
    "healthZone": "red",
    "loginGG": 1,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 23,
    "pagamenti": "overdue",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 1,
    "ticketCS": 3,
    "prioritaCS": true,
    "scansioni": 12,
    "interazioni": 10,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Configurazione menu per evento privato",
    "sintesiInterazione": "Richiesta piatto senza lattosio — pizza con mozzarella vegana",
    "modificheRichieste": 2,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 29
  },
  {
    "id": "recPNwQxA0IparxNS",
    "nome": "Hotel Del Sole",
    "segmento": "Sushi Bar",
    "dataSignup": "2026-01-04",
    "healthScore": 47,
    "healthZone": "yellow",
    "loginGG": 3,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 46,
    "pagamenti": "overdue",
    "fundIdoneo": true,
    "fundStatus": "shown",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 7,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 91,
    "interazioni": 70,
    "postVisti": 2,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Configurazione orari di apertura",
    "sintesiInterazione": "Richiesta versione senza glutine del risotto ai funghi",
    "modificheRichieste": 8,
    "modificheRisolte": 7,
    "interazioneRisolta": false,
    "mediaCoperti": 78
  },
  {
    "id": "recQIFYHZaZpr5nIF",
    "nome": "Bistrot Verdi",
    "segmento": "Osteria",
    "dataSignup": "2025-12-26",
    "healthScore": 69,
    "healthZone": "yellow",
    "loginGG": 10,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 67,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "shown",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 5,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 22,
    "interazioni": 20,
    "postVisti": 1,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Richiesta porzione ridotta per menu bambini",
    "modificheRichieste": 2,
    "modificheRisolte": 2,
    "interazioneRisolta": true,
    "mediaCoperti": 41
  },
  {
    "id": "recQuzAHrp0CSAj4X",
    "nome": "Resort Da Antonio",
    "segmento": "Osteria",
    "dataSignup": "2025-12-04",
    "healthScore": 33,
    "healthZone": "red",
    "loginGG": 2,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 38,
    "pagamenti": "failed",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 4,
    "ticketCS": 1,
    "prioritaCS": true,
    "scansioni": 4,
    "interazioni": 4,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Segnalazione QR code non leggibile su alcuni tavoli",
    "sintesiInterazione": "Aggiunta nota allergeni alla zuppa di pesce",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 31
  },
  {
    "id": "recTN1uOoXAxkn2ko",
    "nome": "Hotel Nuovo Aperto",
    "segmento": "Pub",
    "dataSignup": "2026-03-13",
    "healthScore": 0,
    "healthZone": "unknown",
    "loginGG": 2,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 14,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 0,
    "interazioni": 0,
    "postVisti": 0,
    "tipoUltimaInterazione": "",
    "sintesiChat": "Non riesce a pubblicare il menu — bloccato in bozza",
    "sintesiInterazione": "Nessuna interazione registrata",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 76
  },
  {
    "id": "recTdkK4YXf7bsRHY",
    "nome": "Taverna Bianco",
    "segmento": "Agriturismo",
    "dataSignup": "2025-12-09",
    "healthScore": 69,
    "healthZone": "yellow",
    "loginGG": 4,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 73,
    "pagamenti": "overdue",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 5,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 37,
    "interazioni": 28,
    "postVisti": 3,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Configurazione menu per evento privato",
    "sintesiInterazione": "Cliente chiede il prezzo del menu fisso serale",
    "modificheRichieste": 4,
    "modificheRisolte": 3,
    "interazioneRisolta": false,
    "mediaCoperti": 57
  },
  {
    "id": "recU7RP6zFnziWjtD",
    "nome": "Braceria Il Faro",
    "segmento": "Braceria",
    "dataSignup": "2026-01-14",
    "healthScore": 28,
    "healthZone": "red",
    "loginGG": 0,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 37,
    "pagamenti": "failed",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 4,
    "ticketCS": 4,
    "prioritaCS": true,
    "scansioni": 1,
    "interazioni": 1,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Domanda su esportazione PDF del menu",
    "sintesiInterazione": "Richiesta versione senza glutine del risotto ai funghi",
    "modificheRichieste": 2,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 37
  },
  {
    "id": "recWpwhHtPApmyiBs",
    "nome": "Trattoria Al Lago",
    "segmento": "Osteria",
    "dataSignup": "2025-11-30",
    "healthScore": 100,
    "healthZone": "green",
    "loginGG": 27,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 77,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 334,
    "interazioni": 232,
    "postVisti": 3,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Domanda su esportazione PDF del menu",
    "sintesiInterazione": "Cliente chiede versione light del menu degustazione",
    "modificheRichieste": 5,
    "modificheRisolte": 4,
    "interazioneRisolta": true,
    "mediaCoperti": 78
  },
  {
    "id": "recXr7o55pCjUDkhp",
    "nome": "Enoteca La Brace",
    "segmento": "Trattoria",
    "dataSignup": "2025-11-30",
    "healthScore": 23,
    "healthZone": "red",
    "loginGG": 3,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 11,
    "pagamenti": "overdue",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 4,
    "ticketCS": 5,
    "prioritaCS": true,
    "scansioni": 9,
    "interazioni": 9,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Richiesta attivazione modulo prenotazioni",
    "sintesiInterazione": "Cliente chiede dettagli su piatto del giorno",
    "modificheRichieste": 3,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 43
  },
  {
    "id": "recXxPdD2Mto5ulCg",
    "nome": "Agriturismo Zen",
    "segmento": "Agriturismo",
    "dataSignup": "2025-12-21",
    "healthScore": 62,
    "healthZone": "yellow",
    "loginGG": 9,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 49,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 6,
    "ticketCS": 2,
    "prioritaCS": true,
    "scansioni": 74,
    "interazioni": 66,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Non riesce a pubblicare il menu — bloccato in bozza",
    "sintesiInterazione": "Richiesta aggiunta opzione vegana alla pasta al pesto",
    "modificheRichieste": 1,
    "modificheRisolte": 0,
    "interazioneRisolta": true,
    "mediaCoperti": 80
  },
  {
    "id": "recY3oLtUrdMMpMz0",
    "nome": "Bistrot La Vigna",
    "segmento": "Bistrot",
    "dataSignup": "2025-12-15",
    "healthScore": 54,
    "healthZone": "yellow",
    "loginGG": 4,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 42,
    "pagamenti": "overdue",
    "fundIdoneo": true,
    "fundStatus": "shown",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 7,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 16,
    "interazioni": 12,
    "postVisti": 1,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Richiesta aggiunta opzione vegana alla pasta al pesto",
    "modificheRichieste": 5,
    "modificheRisolte": 3,
    "interazioneRisolta": false,
    "mediaCoperti": 68
  },
  {
    "id": "recZGnHonaTMXHHY3",
    "nome": "Taverna Il Castello",
    "segmento": "Bistrot",
    "dataSignup": "2025-12-02",
    "healthScore": 76,
    "healthZone": "green",
    "loginGG": 18,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 89,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "shown",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 9,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 218,
    "interazioni": 180,
    "postVisti": 4,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Configurazione menu per evento privato",
    "sintesiInterazione": "Modifica prezzi sezione antipasti — aumento stagionale",
    "modificheRichieste": 3,
    "modificheRisolte": 2,
    "interazioneRisolta": false,
    "mediaCoperti": 153
  },
  {
    "id": "recZQkmrkzp5tYbxf",
    "nome": "Resort Del Borgo",
    "segmento": "Braceria",
    "dataSignup": "2026-02-13",
    "healthScore": 4,
    "healthZone": "red",
    "loginGG": 1,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 21,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 3,
    "prioritaCS": true,
    "scansioni": 17,
    "interazioni": 14,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Sostituzione guarnizione sul filetto — preferenza cliente",
    "modificheRichieste": 3,
    "modificheRisolte": 2,
    "interazioneRisolta": false,
    "mediaCoperti": 29
  },
  {
    "id": "recaaBep7zkrfdHU1",
    "nome": "Trattoria Bella Napoli",
    "segmento": "Osteria",
    "dataSignup": "2026-01-04",
    "healthScore": 64,
    "healthZone": "yellow",
    "loginGG": 10,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 54,
    "pagamenti": "failed",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 33,
    "interazioni": 26,
    "postVisti": 2,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Problema con pagamento abbonamento",
    "sintesiInterazione": "Richiesta versione senza glutine del risotto ai funghi",
    "modificheRichieste": 3,
    "modificheRisolte": 1,
    "interazioneRisolta": false,
    "mediaCoperti": 74
  },
  {
    "id": "recala9eMrGdKnrFA",
    "nome": "Pub & Cucina La Fontana",
    "segmento": "Sushi Bar",
    "dataSignup": "2026-01-26",
    "healthScore": 93,
    "healthZone": "green",
    "loginGG": 20,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 82,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 619,
    "interazioni": 512,
    "postVisti": 11,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "NPS basso: difficolta con la sezione foto",
    "sintesiInterazione": "Ordine aperitivo con tagliere — terrazza",
    "modificheRichieste": 10,
    "modificheRisolte": 10,
    "interazioneRisolta": true,
    "mediaCoperti": 62
  },
  {
    "id": "recb38NYQRHNBesS4",
    "nome": "Braceria La Fontana",
    "segmento": "Bistrot",
    "dataSignup": "2026-02-02",
    "healthScore": 1,
    "healthZone": "red",
    "loginGG": 3,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 23,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 5,
    "ticketCS": 1,
    "prioritaCS": true,
    "scansioni": 18,
    "interazioni": 15,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Richiesta attivazione quarta sede",
    "sintesiInterazione": "Sostituzione guarnizione sul filetto — preferenza cliente",
    "modificheRichieste": 1,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 52
  },
  {
    "id": "recbvFPxg0FODVVqS",
    "nome": "Resort Da Nonna Rosa",
    "segmento": "Pizzeria",
    "dataSignup": "2025-11-03",
    "healthScore": 51,
    "healthZone": "yellow",
    "loginGG": 4,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 63,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 76,
    "interazioni": 68,
    "postVisti": 1,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Richiesta supporto per traduzione menu in inglese",
    "sintesiInterazione": "Cliente chiede ingredienti della zuppa di pesce",
    "modificheRichieste": 1,
    "modificheRisolte": 1,
    "interazioneRisolta": true,
    "mediaCoperti": 32
  },
  {
    "id": "reccDD354tAMKoVZe",
    "nome": "Ristorante Rossi",
    "segmento": "Agriturismo",
    "dataSignup": "2025-12-24",
    "healthScore": 21,
    "healthZone": "red",
    "loginGG": 1,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 24,
    "pagamenti": "failed",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 3,
    "ticketCS": 4,
    "prioritaCS": true,
    "scansioni": 2,
    "interazioni": 2,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Richiesta versione senza glutine del risotto ai funghi",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 28
  },
  {
    "id": "reccdU5BKFIr8Q1ot",
    "nome": "Sushi Bar Alla Vecchia Maniera",
    "segmento": "Braceria",
    "dataSignup": "2025-11-17",
    "healthScore": 63,
    "healthZone": "yellow",
    "loginGG": 10,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 74,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 6,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 61,
    "interazioni": 46,
    "postVisti": 3,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Problema con pagamento abbonamento",
    "sintesiInterazione": "Richiesta aggiunta opzione vegana alla pasta al pesto",
    "modificheRichieste": 7,
    "modificheRisolte": 7,
    "interazioneRisolta": false,
    "mediaCoperti": 74
  },
  {
    "id": "reccoeHFAwp3wjEic",
    "nome": "Trattoria Le Colline",
    "segmento": "Trattoria",
    "dataSignup": "2026-02-03",
    "healthScore": 48,
    "healthZone": "yellow",
    "loginGG": 8,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 73,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": null,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 47,
    "interazioni": 39,
    "postVisti": 3,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Nessuna interazione recente",
    "sintesiInterazione": "Richiesta piatto senza lattosio — pizza con mozzarella vegana",
    "modificheRichieste": 7,
    "modificheRisolte": 6,
    "interazioneRisolta": true,
    "mediaCoperti": 53
  },
  {
    "id": "recdGvkcXfFbMYZd7",
    "nome": "Pub & Cucina Fresh",
    "segmento": "Trattoria",
    "dataSignup": "2025-11-26",
    "healthScore": 86,
    "healthZone": "green",
    "loginGG": 27,
    "moduliAttivati": 4,
    "moduliTotali": 5,
    "completezza": 76,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 434,
    "interazioni": 348,
    "postVisti": 8,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "Richiesta attivazione quarta sede",
    "sintesiInterazione": "Ordine room service tramite menu digitale camera 14",
    "modificheRichieste": 16,
    "modificheRisolte": 16,
    "interazioneRisolta": true,
    "mediaCoperti": 73
  },
  {
    "id": "recdgsLUGfK4cvRNy",
    "nome": "Pub & Cucina Da Peppino",
    "segmento": "Resort",
    "dataSignup": "2025-10-23",
    "healthScore": 80,
    "healthZone": "green",
    "loginGG": 20,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 99,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "obtained",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 133,
    "interazioni": 108,
    "postVisti": 11,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "Segnalazione QR code non leggibile su alcuni tavoli",
    "sintesiInterazione": "Ordine take away tramite QR code — pizza margherita x2",
    "modificheRichieste": 8,
    "modificheRisolte": 7,
    "interazioneRisolta": false,
    "mediaCoperti": 124
  },
  {
    "id": "recdm6GsLiVoGodsV",
    "nome": "Trattoria Ai Portici",
    "segmento": "Sushi Bar",
    "dataSignup": "2025-12-25",
    "healthScore": 60,
    "healthZone": "yellow",
    "loginGG": 10,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 70,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": false,
    "nps": 7,
    "ticketCS": 2,
    "prioritaCS": true,
    "scansioni": 86,
    "interazioni": 73,
    "postVisti": 3,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Richiesta supporto per traduzione menu in inglese",
    "sintesiInterazione": "Richiesta piatto senza lattosio — pizza con mozzarella vegana",
    "modificheRichieste": 1,
    "modificheRisolte": 0,
    "interazioneRisolta": true,
    "mediaCoperti": 69
  },
  {
    "id": "recebRdpS018Pf5Vg",
    "nome": "Taverna Fuji",
    "segmento": "Bistrot",
    "dataSignup": "2026-01-19",
    "healthScore": 84,
    "healthZone": "green",
    "loginGG": 25,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 93,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 9,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 270,
    "interazioni": 189,
    "postVisti": 5,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Problema upload foto secondi piatti",
    "sintesiInterazione": "Info vini in abbinamento al menu degustazione",
    "modificheRichieste": 19,
    "modificheRisolte": 19,
    "interazioneRisolta": true,
    "mediaCoperti": 41
  },
  {
    "id": "recedqC80RFDTf59t",
    "nome": "Bistrot Da Marco",
    "segmento": "Pizzeria",
    "dataSignup": "2025-12-12",
    "healthScore": 53,
    "healthZone": "yellow",
    "loginGG": 4,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 47,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 6,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 98,
    "interazioni": 71,
    "postVisti": 2,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Sostituzione guarnizione sul filetto — preferenza cliente",
    "modificheRichieste": 3,
    "modificheRisolte": 2,
    "interazioneRisolta": false,
    "mediaCoperti": 51
  },
  {
    "id": "recfqz8wRD7FLOght",
    "nome": "Osteria Il Faro",
    "segmento": "Pizzeria",
    "dataSignup": "2025-09-05",
    "healthScore": 78,
    "healthZone": "green",
    "loginGG": 12,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 97,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 8,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 228,
    "interazioni": 174,
    "postVisti": 8,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "NPS basso: difficolta con la sezione foto",
    "sintesiInterazione": "Ordine room service tramite menu digitale camera 14",
    "modificheRichieste": 14,
    "modificheRisolte": 14,
    "interazioneRisolta": true,
    "mediaCoperti": 66
  },
  {
    "id": "rech9HvSnG6QK73ic",
    "nome": "Ristorante Siciliana",
    "segmento": "Trattoria",
    "dataSignup": "2025-10-28",
    "healthScore": 57,
    "healthZone": "yellow",
    "loginGG": 10,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 43,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 8,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 35,
    "interazioni": 26,
    "postVisti": 2,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Richiesta porzione ridotta per menu bambini",
    "modificheRichieste": 8,
    "modificheRisolte": 8,
    "interazioneRisolta": false,
    "mediaCoperti": 60
  },
  {
    "id": "rechPhcuDm7M80ECr",
    "nome": "Locanda Veneto",
    "segmento": "Ristorante",
    "dataSignup": "2025-10-18",
    "healthScore": 89,
    "healthZone": "green",
    "loginGG": 14,
    "moduliAttivati": 4,
    "moduliTotali": 5,
    "completezza": 87,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "obtained",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 276,
    "interazioni": 197,
    "postVisti": 11,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "Configurazione orari di apertura",
    "sintesiInterazione": "Ordine take away tramite QR code — pizza margherita x2",
    "modificheRichieste": 11,
    "modificheRisolte": 11,
    "interazioneRisolta": true,
    "mediaCoperti": 42
  },
  {
    "id": "rechXGWhtbt7psUbF",
    "nome": "Osteria La Vigna",
    "segmento": "Ristorante",
    "dataSignup": "2026-03-10",
    "healthScore": 0,
    "healthZone": "unknown",
    "loginGG": 1,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 10,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 0,
    "interazioni": 0,
    "postVisti": 0,
    "tipoUltimaInterazione": "",
    "sintesiChat": "Richiesta supporto per traduzione menu in inglese",
    "sintesiInterazione": "Nessuna interazione registrata",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 46
  },
  {
    "id": "reciHjlcPLk4arHaG",
    "nome": "Hotel La Quercia",
    "segmento": "Agriturismo",
    "dataSignup": "2026-01-23",
    "healthScore": 44,
    "healthZone": "yellow",
    "loginGG": 8,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 72,
    "pagamenti": "overdue",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 7,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 71,
    "interazioni": 53,
    "postVisti": 2,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Richiesta attivazione modulo prenotazioni",
    "sintesiInterazione": "Cliente chiede versione light del menu degustazione",
    "modificheRichieste": 2,
    "modificheRisolte": 2,
    "interazioneRisolta": false,
    "mediaCoperti": 72
  },
  {
    "id": "recikFCTOe6bsmDd8",
    "nome": "Taverna Toscana",
    "segmento": "Bar Ristorante",
    "dataSignup": "2025-11-04",
    "healthScore": 44,
    "healthZone": "yellow",
    "loginGG": 6,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 49,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 6,
    "ticketCS": 2,
    "prioritaCS": true,
    "scansioni": 87,
    "interazioni": 67,
    "postVisti": 3,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Domanda su esportazione PDF del menu",
    "sintesiInterazione": "Domanda su presenza crostacei nel ramen di miso",
    "modificheRichieste": 6,
    "modificheRisolte": 4,
    "interazioneRisolta": true,
    "mediaCoperti": 54
  },
  {
    "id": "recj02Ar3HBmRQTrq",
    "nome": "Ristorante Del Porto",
    "segmento": "Agriturismo",
    "dataSignup": "2025-11-19",
    "healthScore": 53,
    "healthZone": "yellow",
    "loginGG": 4,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 44,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 5,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 14,
    "interazioni": 13,
    "postVisti": 2,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Non riesce a pubblicare il menu — bloccato in bozza",
    "sintesiInterazione": "Aggiornamento descrizione secondo piatto — nuova ricetta",
    "modificheRichieste": 7,
    "modificheRisolte": 6,
    "interazioneRisolta": true,
    "mediaCoperti": 54
  },
  {
    "id": "recjpYuIFrgLcxROz",
    "nome": "Enoteca Ichiban",
    "segmento": "Osteria",
    "dataSignup": "2026-01-05",
    "healthScore": 5,
    "healthZone": "red",
    "loginGG": 2,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 21,
    "pagamenti": "overdue",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 4,
    "ticketCS": 2,
    "prioritaCS": true,
    "scansioni": 6,
    "interazioni": 5,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Domanda su esportazione PDF del menu",
    "sintesiInterazione": "Cliente vuole sostituire la carne con alternativa vegetariana",
    "modificheRichieste": 2,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 39
  },
  {
    "id": "reck6XkE2M8xeS9OS",
    "nome": "Resort Del Chianti",
    "segmento": "Bar Ristorante",
    "dataSignup": "2025-09-22",
    "healthScore": 75,
    "healthZone": "green",
    "loginGG": 13,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 77,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 299,
    "interazioni": 202,
    "postVisti": 6,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "Configurazione menu per evento privato",
    "sintesiInterazione": "Ordine aperitivo con tagliere — terrazza",
    "modificheRichieste": 4,
    "modificheRisolte": 4,
    "interazioneRisolta": true,
    "mediaCoperti": 143
  },
  {
    "id": "reck8BMZIwJMAfoDh",
    "nome": "Braceria Alla Vecchia Maniera",
    "segmento": "Resort",
    "dataSignup": "2025-11-19",
    "healthScore": 67,
    "healthZone": "yellow",
    "loginGG": 10,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 54,
    "pagamenti": "overdue",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 6,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 31,
    "interazioni": 28,
    "postVisti": 2,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Domanda se il locale e adatto a celiaci",
    "modificheRichieste": 5,
    "modificheRisolte": 3,
    "interazioneRisolta": true,
    "mediaCoperti": 77
  },
  {
    "id": "recly29UwDkYCYZLM",
    "nome": "Taverna La Vigna",
    "segmento": "Osteria",
    "dataSignup": "2026-03-14",
    "healthScore": 0,
    "healthZone": "unknown",
    "loginGG": 3,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 9,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 0,
    "interazioni": 0,
    "postVisti": 0,
    "tipoUltimaInterazione": "",
    "sintesiChat": "Configurazione menu per evento privato",
    "sintesiInterazione": "Nessuna interazione registrata",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 26
  },
  {
    "id": "recn389N0R64COLSS",
    "nome": "Enoteca Del Mercato",
    "segmento": "Pub",
    "dataSignup": "2026-01-19",
    "healthScore": 10,
    "healthZone": "red",
    "loginGG": 3,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 33,
    "pagamenti": "failed",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 4,
    "ticketCS": 3,
    "prioritaCS": true,
    "scansioni": 18,
    "interazioni": 15,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Info su provenienza della carne Angus",
    "modificheRichieste": 3,
    "modificheRisolte": 2,
    "interazioneRisolta": false,
    "mediaCoperti": 52
  },
  {
    "id": "recnpfv447diZjmPY",
    "nome": "Agriturismo Bella Napoli",
    "segmento": "Braceria",
    "dataSignup": "2025-10-01",
    "healthScore": 82,
    "healthZone": "green",
    "loginGG": 26,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 83,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 569,
    "interazioni": 450,
    "postVisti": 12,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Problema upload foto secondi piatti",
    "sintesiInterazione": "Info allergeni sulla margherita classica",
    "modificheRichieste": 19,
    "modificheRisolte": 18,
    "interazioneRisolta": true,
    "mediaCoperti": 142
  },
  {
    "id": "recosCI2hZaiH5yfo",
    "nome": "Sushi Bar Il Tramonto",
    "segmento": "Pub",
    "dataSignup": "2025-12-28",
    "healthScore": 43,
    "healthZone": "yellow",
    "loginGG": 7,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 59,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 8,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 93,
    "interazioni": 73,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "NPS basso: difficolta con la sezione foto",
    "sintesiInterazione": "Richiesta versione senza glutine del risotto ai funghi",
    "modificheRichieste": 4,
    "modificheRisolte": 2,
    "interazioneRisolta": true,
    "mediaCoperti": 32
  },
  {
    "id": "recp3cSQBKWeZW6Rd",
    "nome": "Pizzeria Al Ponte",
    "segmento": "Bistrot",
    "dataSignup": "2026-02-01",
    "healthScore": 93,
    "healthZone": "green",
    "loginGG": 29,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 86,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 412,
    "interazioni": 284,
    "postVisti": 3,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Configurazione orari di apertura",
    "sintesiInterazione": "Cliente vuole sostituire la carne con alternativa vegetariana",
    "modificheRichieste": 10,
    "modificheRisolte": 10,
    "interazioneRisolta": true,
    "mediaCoperti": 103
  },
  {
    "id": "recpuU0iV4RMzacxe",
    "nome": "Locanda Del Chianti",
    "segmento": "Ristorante",
    "dataSignup": "2026-02-07",
    "healthScore": 51,
    "healthZone": "yellow",
    "loginGG": 9,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 58,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "shown",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 8,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 83,
    "interazioni": 60,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Problema con pagamento abbonamento",
    "sintesiInterazione": "Aggiunta nota allergeni alla zuppa di pesce",
    "modificheRichieste": 4,
    "modificheRisolte": 3,
    "interazioneRisolta": false,
    "mediaCoperti": 39
  },
  {
    "id": "recqq0WwBxsylJSdR",
    "nome": "Bistrot Alla Vecchia Maniera",
    "segmento": "Pub",
    "dataSignup": "2026-02-16",
    "healthScore": 16,
    "healthZone": "red",
    "loginGG": 1,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 40,
    "pagamenti": "overdue",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 1,
    "ticketCS": 2,
    "prioritaCS": true,
    "scansioni": 2,
    "interazioni": 2,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Segnalazione QR code non leggibile su alcuni tavoli",
    "sintesiInterazione": "Richiesta aggiunta opzione vegana alla pasta al pesto",
    "modificheRichieste": 4,
    "modificheRisolte": 1,
    "interazioneRisolta": false,
    "mediaCoperti": 59
  },
  {
    "id": "recqsqo7rr8IiLjKb",
    "nome": "Pizzeria Da Salvatore",
    "segmento": "Braceria",
    "dataSignup": "2025-11-22",
    "healthScore": 96,
    "healthZone": "green",
    "loginGG": 23,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 81,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 464,
    "interazioni": 318,
    "postVisti": 7,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Preordine tavolo 6 — antipasto e primo per 4 persone",
    "modificheRichieste": 17,
    "modificheRisolte": 17,
    "interazioneRisolta": true,
    "mediaCoperti": 60
  },
  {
    "id": "recr3GuWqZ0jAo27n",
    "nome": "Hotel Il Belvedere",
    "segmento": "Bar Ristorante",
    "dataSignup": "2026-02-07",
    "healthScore": 29,
    "healthZone": "red",
    "loginGG": 2,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 21,
    "pagamenti": "overdue",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 6,
    "ticketCS": 2,
    "prioritaCS": true,
    "scansioni": 9,
    "interazioni": 8,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Configurazione orari di apertura",
    "sintesiInterazione": "Info vini in abbinamento al menu degustazione",
    "modificheRichieste": 1,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 61
  },
  {
    "id": "recrXWTu6JJeZhPrv",
    "nome": "Enoteca Al Ponte",
    "segmento": "Pub",
    "dataSignup": "2026-02-13",
    "healthScore": 42,
    "healthZone": "yellow",
    "loginGG": 4,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 67,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "shown",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": false,
    "nps": 7,
    "ticketCS": 2,
    "prioritaCS": true,
    "scansioni": 74,
    "interazioni": 55,
    "postVisti": 0,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Richiesta attivazione quarta sede",
    "sintesiInterazione": "Richiesta porzione ridotta per menu bambini",
    "modificheRichieste": 7,
    "modificheRisolte": 5,
    "interazioneRisolta": false,
    "mediaCoperti": 51
  },
  {
    "id": "recrcGQTQsqcFrkWp",
    "nome": "Braceria Mediterraneo",
    "segmento": "Bar Ristorante",
    "dataSignup": "2026-02-15",
    "healthScore": 42,
    "healthZone": "yellow",
    "loginGG": 6,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 66,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 7,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 33,
    "interazioni": 29,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Configurazione menu per evento privato",
    "sintesiInterazione": "Domanda se il locale e adatto a celiaci",
    "modificheRichieste": 2,
    "modificheRisolte": 1,
    "interazioneRisolta": false,
    "mediaCoperti": 28
  },
  {
    "id": "recroAsQ74Zzy5z1N",
    "nome": "Braceria Al Campanile",
    "segmento": "Agriturismo",
    "dataSignup": "2025-11-30",
    "healthScore": 42,
    "healthZone": "yellow",
    "loginGG": 8,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 74,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 8,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 64,
    "interazioni": 46,
    "postVisti": 1,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Domanda su esportazione PDF del menu",
    "sintesiInterazione": "Aggiunta nota allergeni alla zuppa di pesce",
    "modificheRichieste": 7,
    "modificheRisolte": 7,
    "interazioneRisolta": true,
    "mediaCoperti": 65
  },
  {
    "id": "recrr5i2mFx7o4x11",
    "nome": "Ristorante Recente",
    "segmento": "Trattoria",
    "dataSignup": "2025-10-30",
    "healthScore": 88,
    "healthZone": "green",
    "loginGG": 29,
    "moduliAttivati": 3,
    "moduliTotali": 5,
    "completezza": 88,
    "pagamenti": "ok",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 9,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 414,
    "interazioni": 295,
    "postVisti": 3,
    "tipoUltimaInterazione": "ordine",
    "sintesiChat": "Configurazione menu per evento privato",
    "sintesiInterazione": "Prenotazione cena con menu degustazione — 8 persone",
    "modificheRichieste": 14,
    "modificheRisolte": 14,
    "interazioneRisolta": true,
    "mediaCoperti": 131
  },
  {
    "id": "rect7Befntduz9HZa",
    "nome": "Pizzeria Il Rifugio",
    "segmento": "Bar Ristorante",
    "dataSignup": "2026-03-11",
    "healthScore": 0,
    "healthZone": "unknown",
    "loginGG": 4,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 17,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 0,
    "interazioni": 0,
    "postVisti": 0,
    "tipoUltimaInterazione": "",
    "sintesiChat": "Domanda su integrazione con sistema cassa",
    "sintesiInterazione": "Nessuna interazione registrata",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 72
  },
  {
    "id": "rectfl40bpRDV2fJp",
    "nome": "Enoteca Tokyo Garden",
    "segmento": "Bar Ristorante",
    "dataSignup": "2025-11-29",
    "healthScore": 86,
    "healthZone": "green",
    "loginGG": 17,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 78,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "applied",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 10,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 660,
    "interazioni": 462,
    "postVisti": 6,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Configurazione menu per evento privato",
    "sintesiInterazione": "Aggiornamento descrizione secondo piatto — nuova ricetta",
    "modificheRichieste": 19,
    "modificheRisolte": 19,
    "interazioneRisolta": true,
    "mediaCoperti": 79
  },
  {
    "id": "rectrlfBDioPdjc6h",
    "nome": "Pizzeria La Pergola",
    "segmento": "Sushi Bar",
    "dataSignup": "2026-03-17",
    "healthScore": 0,
    "healthZone": "unknown",
    "loginGG": 4,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 25,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 0,
    "interazioni": 0,
    "postVisti": 0,
    "tipoUltimaInterazione": "",
    "sintesiChat": "Problema con pagamento abbonamento",
    "sintesiInterazione": "Nessuna interazione registrata",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 54
  },
  {
    "id": "rectyb4iP0ev9yUQQ",
    "nome": "Bar Ristorante Ichiban",
    "segmento": "Osteria",
    "dataSignup": "2026-03-18",
    "healthScore": 0,
    "healthZone": "unknown",
    "loginGG": 3,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 19,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 0,
    "interazioni": 0,
    "postVisti": 0,
    "tipoUltimaInterazione": "",
    "sintesiChat": "Configurazione menu per evento privato",
    "sintesiInterazione": "Nessuna interazione registrata",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 61
  },
  {
    "id": "recupZ4ZSwr9pdzY1",
    "nome": "Braceria Al Lago",
    "segmento": "Agriturismo",
    "dataSignup": "2025-10-26",
    "healthScore": 59,
    "healthZone": "yellow",
    "loginGG": 10,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 54,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 6,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 30,
    "interazioni": 22,
    "postVisti": 1,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Configurazione orari di apertura",
    "sintesiInterazione": "Richiesta aggiunta opzione vegana alla pasta al pesto",
    "modificheRichieste": 5,
    "modificheRisolte": 4,
    "interazioneRisolta": true,
    "mediaCoperti": 65
  },
  {
    "id": "recvhMUPgf16JWsTl",
    "nome": "Sushi Bar Da Antonio",
    "segmento": "Agriturismo",
    "dataSignup": "2025-11-05",
    "healthScore": 62,
    "healthZone": "yellow",
    "loginGG": 8,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 67,
    "pagamenti": "overdue",
    "fundIdoneo": false,
    "fundStatus": "not_reached",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": false,
    "nps": 8,
    "ticketCS": 1,
    "prioritaCS": false,
    "scansioni": 61,
    "interazioni": 53,
    "postVisti": 2,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Configurazione orari di apertura",
    "sintesiInterazione": "Modifica prezzi sezione antipasti — aumento stagionale",
    "modificheRichieste": 2,
    "modificheRisolte": 0,
    "interazioneRisolta": true,
    "mediaCoperti": 72
  },
  {
    "id": "recwA3aID8yYc29Km",
    "nome": "Locanda Da Salvatore",
    "segmento": "Trattoria",
    "dataSignup": "2026-01-26",
    "healthScore": 58,
    "healthZone": "yellow",
    "loginGG": 6,
    "moduliAttivati": 1,
    "moduliTotali": 5,
    "completezza": 61,
    "pagamenti": "overdue",
    "fundIdoneo": true,
    "fundStatus": "shown",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": null,
    "ticketCS": 2,
    "prioritaCS": true,
    "scansioni": 36,
    "interazioni": 32,
    "postVisti": 2,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Difficolta aggiornamento prezzi stagionali",
    "sintesiInterazione": "Info vini in abbinamento al menu degustazione",
    "modificheRichieste": 3,
    "modificheRisolte": 3,
    "interazioneRisolta": false,
    "mediaCoperti": 76
  },
  {
    "id": "recweDT0a5dvHEnQe",
    "nome": "Bistrot Il Tramonto",
    "segmento": "Sushi Bar",
    "dataSignup": "2025-11-06",
    "healthScore": 83,
    "healthZone": "green",
    "loginGG": 29,
    "moduliAttivati": 4,
    "moduliTotali": 5,
    "completezza": 86,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "applied",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 9,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 498,
    "interazioni": 403,
    "postVisti": 4,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Non riesce a pubblicare il menu — bloccato in bozza",
    "sintesiInterazione": "Aggiornamento descrizione secondo piatto — nuova ricetta",
    "modificheRichieste": 8,
    "modificheRisolte": 8,
    "interazioneRisolta": true,
    "mediaCoperti": 89
  },
  {
    "id": "recyIwk9OVIzwJDq3",
    "nome": "Locanda La Vigna",
    "segmento": "Agriturismo",
    "dataSignup": "2025-10-05",
    "healthScore": 84,
    "healthZone": "green",
    "loginGG": 25,
    "moduliAttivati": 5,
    "moduliTotali": 5,
    "completezza": 93,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "shown",
    "setupCompleto": true,
    "productTour": true,
    "d7Survey": true,
    "nps": 8,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 760,
    "interazioni": 555,
    "postVisti": 10,
    "tipoUltimaInterazione": "modifica",
    "sintesiChat": "Domanda su esportazione PDF del menu",
    "sintesiInterazione": "Richiesta piatto senza lattosio — pizza con mozzarella vegana",
    "modificheRichieste": 13,
    "modificheRisolte": 13,
    "interazioneRisolta": true,
    "mediaCoperti": 102
  },
  {
    "id": "recyQt3idjcm8SqeU",
    "nome": "Enoteca Il Tramonto",
    "segmento": "Bistrot",
    "dataSignup": "2026-03-14",
    "healthScore": 0,
    "healthZone": "unknown",
    "loginGG": 2,
    "moduliAttivati": 0,
    "moduliTotali": 5,
    "completezza": 6,
    "pagamenti": "ok",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": null,
    "ticketCS": 0,
    "prioritaCS": false,
    "scansioni": 0,
    "interazioni": 0,
    "postVisti": 0,
    "tipoUltimaInterazione": "",
    "sintesiChat": "Richiesta attivazione modulo prenotazioni",
    "sintesiInterazione": "Nessuna interazione registrata",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 26
  },
  {
    "id": "recyb61iYMKTShI3G",
    "nome": "Agriturismo La Quercia",
    "segmento": "Resort",
    "dataSignup": "2025-12-26",
    "healthScore": 31,
    "healthZone": "red",
    "loginGG": 2,
    "moduliAttivati": 2,
    "moduliTotali": 5,
    "completezza": 18,
    "pagamenti": "failed",
    "fundIdoneo": true,
    "fundStatus": "not_reached",
    "setupCompleto": false,
    "productTour": false,
    "d7Survey": false,
    "nps": 5,
    "ticketCS": 3,
    "prioritaCS": true,
    "scansioni": 5,
    "interazioni": 5,
    "postVisti": 0,
    "tipoUltimaInterazione": "info",
    "sintesiChat": "Problema upload foto secondi piatti",
    "sintesiInterazione": "Domanda su certificazione biologica delle verdure",
    "modificheRichieste": 0,
    "modificheRisolte": 0,
    "interazioneRisolta": false,
    "mediaCoperti": 47
  }
];